import { Expense, Income, Invoice, TaxSummary, User } from '@/models'

export const user_data: Array<User> = []
export const tax_summary_data: Array<TaxSummary> = []
export const invoice_data: Array<Invoice> = [
  {
    id: 'INV-001',
    clientName: 'Acme Corp',
    clientEmail: 'billing@acme.com',
    dateIssued: '2025-07-01',
    dueDate: '2025-07-15',
    items: [
      { description: 'Website Design', quantity: 1, unitPrice: 1500 },
      { description: 'Hosting (1 year)', quantity: 1, unitPrice: 120 },
    ],
    taxRate: 0.18,
    total: 1903.6,
    status: 'sent',
  },
  {
    id: 'INV-002',
    clientName: 'Beta LLC',
    clientEmail: 'finance@beta.com',
    dateIssued: '2025-07-05',
    dueDate: '2025-07-20',
    items: [
      { description: 'Mobile App Development', quantity: 50, unitPrice: 50 },
    ],
    taxRate: 0.18,
    total: 2950,
    status: 'paid',
  },
  {
    id: 'INV-003',
    clientName: 'Gamma Solutions',
    clientEmail: 'accounts@gamma.com',
    dateIssued: '2025-07-10',
    dueDate: '2025-07-25',
    items: [{ description: 'Maintenance', quantity: 12, unitPrice: 100 }],
    taxRate: 0.18,
    total: 1416,
    status: 'overdue',
  },
  {
    id: 'INV-004',
    clientName: 'Delta Inc.',
    clientEmail: 'info@delta.com',
    dateIssued: '2025-07-12',
    dueDate: '2025-07-30',
    items: [{ description: 'SEO Services', quantity: 6, unitPrice: 200 }],
    taxRate: 0.18,
    total: 1416,
    status: 'draft',
  },
  {
    id: 'INV-005',
    clientName: 'Orion Tech',
    clientEmail: 'contact@oriontech.com',
    dateIssued: '2025-08-01',
    dueDate: '2025-08-15',
    items: [
      { description: 'Cloud Migration', quantity: 20, unitPrice: 200 },
      { description: 'Support Plan', quantity: 1, unitPrice: 500 },
    ],
    taxRate: 0.18,
    total: 5300,
    status: 'sent',
  },
  {
    id: 'INV-006',
    clientName: 'Phoenix Media',
    clientEmail: 'accounts@phoenixmedia.com',
    dateIssued: '2025-08-03',
    dueDate: '2025-08-18',
    items: [
      { description: 'Social Media Campaign', quantity: 3, unitPrice: 800 },
    ],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-007',
    clientName: 'Titan Logistics',
    clientEmail: 'finance@titanlogistics.com',
    dateIssued: '2025-08-05',
    dueDate: '2025-08-20',
    items: [
      { description: 'Fleet Maintenance', quantity: 5, unitPrice: 400 },
      {
        description: 'Route Optimization Software',
        quantity: 1,
        unitPrice: 1200,
      },
    ],
    taxRate: 0.18,
    total: 3540,
    status: 'overdue',
  },
  {
    id: 'INV-008',
    clientName: 'Nova Retail',
    clientEmail: 'billing@novaretail.com',
    dateIssued: '2025-08-07',
    dueDate: '2025-08-22',
    items: [
      { description: 'POS System Upgrade', quantity: 2, unitPrice: 1500 },
    ],
    taxRate: 0.18,
    total: 3540,
    status: 'draft',
  },
  {
    id: 'INV-009',
    clientName: 'Atlas Construction',
    clientEmail: 'admin@atlasconstruction.com',
    dateIssued: '2025-08-10',
    dueDate: '2025-08-25',
    items: [
      { description: 'Safety Training', quantity: 10, unitPrice: 150 },
      { description: 'Consulting Services', quantity: 5, unitPrice: 300 },
    ],
    taxRate: 0.18,
    total: 2655,
    status: 'sent',
  },
  {
    id: 'INV-010',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-11',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-12',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-13',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-14',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
  {
    id: 'INV-15',
    clientName: 'Vega Health',
    clientEmail: 'finance@vegahealth.com',
    dateIssued: '2025-08-12',
    dueDate: '2025-08-27',
    items: [{ description: 'Wellness Program', quantity: 2, unitPrice: 1200 }],
    taxRate: 0.18,
    total: 2832,
    status: 'paid',
  },
]
export const income_data: Array<Income> = []
export const expense_data: Array<Expense> = []
